[tool.poetry]
name = "dbt_bootcamp"
version = "0.1.0"
description = ""
authors = ["Aldo"]

[tool.poetry.dependencies]
python = "^3.9"
dbt-trino = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
